.github/workflows/pull-request-title-validation.yml
Fix PR title validation get triggered when merge to main
Fixes https://github.com/benbenbang/types-confluent-kafka/issues/3
=> fix(ci): remove pr-title check trigger when merge to main

.github/release.yml
remove `development` from release note if it's triggered by `gh`
=> ci: exclude development label in release notes

confluent_kafka-stubs/_util/validation_util.pyi, confluent_kafka-stubs/admin/__init__.pyi, confluent_kafka-stubs/admin/_acl.pyi, confluent_kafka-stubs/avro/cached_schema_registry_client.pyi
since python constraints to `>= 3.8`, no need to backward compat
resolve #110
=> refactor: clean up string type py2 compat

confluent_kafka-stubs/admin/__init__.pyi, confluent_kafka-stubs/avro/__init__.pyi, confluent_kafka-stubs/avro/error.pyi, confluent_kafka-stubs/avro/load.pyi, confluent_kafka-stubs/avro/serializer/message_serializer.pyi, confluent_kafka-stubs/error.pyi, confluent_kafka-stubs/serialization/__init__.pyi
replace some import ref from using `confluent_kafka` directly
resolve #125
=> refactor: use relative import from `this` typing package

confluent_kafka-stubs/schema_registry/avro.pyi
Corrects the `to_dict`/`from_dict` Callable signatures for Avro serialization.
https://github.com/benbenbang/types-confluent-kafka/issues/154
=> fix: Correct to/from dict callables for Avro serializers

confluent_kafka-stubs/admin/__init__.pyi
⚠️ Noted that the latest version of Confluent Kafka Python is `2.3.x` now.
- For introducing new signatures, please use `feat`
- For fixing compatible signature in `2.2.x`, please use `fix`
Switch from `asyncio.Future `to  `concurrent.futures import Future`.
Closes #197 
- [x ] Bug fix (non-breaking change which fixes an issue)
Any additional context, explanation, or reasoning for the changes made.
If applicable, provide screenshots or images to visually represent the changes.
=> fix: use concurrent.future.Future instead of asyncio.Future

confluent_kafka-stubs/admin/__init__.pyi
feat: add missing bool to AdminClient create_partitions method
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/_modules/confluent_kafka/admin.html#AdminClient.create_partitions
⚠️ Noted that the latest version of Confluent Kafka Python is `2.3.x` now.
- For introducing new signatures, please use `feat`
- For fixing compatible signature in `2.2.x`, please use `fix`
feat: add missing bool to AdminClient create_partitions method
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/_modules/confluent_kafka/admin.html#AdminClient.create_partitions
2.2.0 reference -> [confluent docs](https://docs.confluent.io/platform/7.4/clients/confluent-kafka-python/html/index.html#confluent_kafka.admin.AdminClient.create_partitions_
If this pull …
=> fix: add missing bool to AdminClient create_partitions method

pyproject.toml
⚠️ Please make sure:
---
This pull request includes a small change to the `pyproject.toml` file. The change adds specific linting rules to ignore certain error codes.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R75-R77): Added `ignore = ["F821", "F822"]` to the `[tool.ruff.lint]` section to exclude specific linting errors.
Any additional context, explanation, or reasoning for the changes made.
If applicable, provide screenshots or images to visually represent the changes.
=> ci(workflow): diable ruff F821, F822

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pull-request.yml
This pull request includes a small change to the GitHub Actions workflow configuration in the `.github/workflows/pull-request.yml` file. The change introduces a new event trigger for `pull_request_target` to the existing workflow.
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0R7-R9): Added `pull_request_target` event trigger for the `main` branch.
- [x\  I have commented my code, particularly in hard-to-understand areas.
=> ci(workflow): add pr target on to allow forked repo use labeler

confluent_kafka-stubs/cimpl.pyi
Added `TopicPartition.error`, documented here: https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.TopicPartition.error
https://github.com/benbenbang/types-confluent-kafka/issues/234
=> fix: add TopicPartition.error

confluent_kafka-stubs/avro/__init__.pyi, confluent_kafka-stubs/cimpl.pyi, confluent_kafka-stubs/serializing_producer.pyi
⚠️ Please make sure:
---
`on_delivery`, one of the current parameters of `Producer.produce`, is an alias for `callback` which is missing, since almost the beginning like `confluent-kafka-0.9.12`.
https://github.com/confluentinc/confluent-kafka-python/blob/v0.9.1.2/confluent_kafka/src/Producer.c#L252-L253
https://github.com/confluentinc/confluent-kafka-python/blob/v0.9.1.2/confluent_kafka/src/Producer.c#L367-L368
https://github.com/confluentinc/confluent-kafka-python/commit/6d90fa726a81f68d324d14da1f77103b46c51a05#diff-60b27e7323e9765c71d52efdd6914856b0a776f327f1c6e51c64f8564644faaa
N/A
https://github.com/confluentinc/confluent-kafka-python/blob/v2.10.1/README.md?plain=1#L58
https://github.com/confluentinc/confluent-kafka-python/blob/v2.10.1/docs …
=> fix: add callback as original parameter for produce alias on_delivery

.github/workflows/main.yml, pyproject.toml, uv.lock
This pull request includes updates to the CI configuration and dependency management, as well as the removal of `pylint` configuration in favor of `ruff`. The most important changes include upgrading the pre-commit container image to Python 3.12, adding linting dependencies, and switching linting tools from `pylint` to `ruff`.
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L16-R16): Upgraded the pre-commit container image from Python 3.11 to Python 3.12 to ensure compatibility with the latest Python version.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R43-R46): Added a new `lint` dependency group with `pre-commit>=4.2.0` and `ruff>=0.12.2` to manage linting tools.
* …
=> ci(workflow): update default py version & add missing linting packages

.github/workflows/publish.yml, .github/workflows/publishrc.yml, .github/workflows/release-cp.yml
This pull request updates several GitHub Actions workflows to improve compatibility and streamline the build process. Key changes include upgrading Python versions, modifying container images, and adding the `--no-sources` flag to `uv build` commands.
* [`.github/workflows/release-cp.yml`](diffhunk://#diff-fd96c6cb4d9ffec6ca4a96d44bb6ca11d54b1d8f5418dce91fdbb4487b224ba4L52-R52): Updated the container image to use Python 3.12 (`ghcr.io/${{ github.repository }}/pre-commit:py3.12`) and changed the Python setup to version 3.12. [[1]](diffhunk://#diff-fd96c6cb4d9ffec6ca4a96d44bb6ca11d54b1d8f5418dce91fdbb4487b224ba4L52-R52) [[2]](diffhunk://#diff-fd96c6cb4d9ffec6ca4a96d44bb6ca11d54b1d8f5418dce91fdbb4487b224ba4L63-R63)
* [`.github/workflows/publish.yml`](diffhunk://#diff-551d1fcf87f78cc3bc18a7b33 …
=> ci(workflow): suppress instrumented tooling from uv to build pkg

.github/workflows/pull-request-target.yml, .github/workflows/pull-request.yml
This pull request makes changes to GitHub Actions workflows to improve concurrency handling and enhance pre-commit checks. The most important updates include modifying the concurrency group in `.github/workflows/pull-request-target.yml` and replacing the pre-commit workflow in `.github/workflows/pull-request.yml` with a detailed setup and execution process.
* [`.github/workflows/pull-request-target.yml`](diffhunk://#diff-ef5ba6d24a13fb62d98bd915d166833f97a83f114f26af945e8d0939e26ec140L14-R14): Updated the `concurrency` group to use `target` instead of `labeler`, ensuring more accurate grouping for pull request events.
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0L20-R58): Replaced the `pre-commit` job with a …
=> ci(workflows): drop reusable pre-commit

confluent_kafka-stubs/avro/cached_schema_registry_client.pyi
This pull request introduces a default value for the `max_schemas_per_subject` parameter in the `CachedSchemaRegistryClient` class constructor. The change enhances usability by eliminating the need to explicitly specify this parameter in most cases.
* [`confluent_kafka-stubs/avro/cached_schema_registry_client.pyi`](diffhunk://#diff-42e6f1f78a3cc4e7338e7ce6365bb20a78fd676378e55579e8a24be502824f51L41-R41): Added a default value of `1000` to the `max_schemas_per_subject` parameter in the `__init__` method of the `CachedSchemaRegistryClient` class.
resolve #208
=> refactor(avro): add missing default value for CachedSchemaRegistryClient

.github/workflows/release.yml
This pull request makes a minor adjustment to the `.github/workflows/release.yml` file. It removes the `python_version` and `uv_version` parameters from the `jobs` configuration.
=> fix(workflows): remove non exist inputs

pyproject.toml
This pull request updates the documentation URL in the `pyproject.toml` file to point to a new location.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L59-R59): Changed the `Documentation` URL from "https://readthedocs.org" to "https://benbenbang.github.io/types-confluent-kafka/" to reflect the updated hosting for the project's documentation.
=> build(config): update project metadata

pyproject.toml, uv.lock
This pull request includes updates to the `pyproject.toml` file, focusing on adjusting Python version constraints and reformatting the `lint` dependency list for consistency.
* Updated the `requires-python` field to allow Python versions `<3.14` instead of `<=3.13`, ensuring compatibility with future Python releases. (`pyproject.toml`, [pyproject.tomlL33-R33](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L33-R33))
* Reformatted the `lint` dependency list from a multi-line format to a single-line format for consistency with other dependency groups. (`pyproject.toml`, [pyproject.tomlL51-R51](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L51-R51))
=> refactor: update python version constraint

.github/workflows/versioning.yml
This pull request updates the `.github/workflows/versioning.yml` file to make the workflow more dynamic by using input variables for Python and `uv` versions. This change allows greater flexibility when triggering the workflow.
Key changes:
* Updated the `python-version` in the `set python` step to use the `github.event.inputs.python_version` variable instead of a hardcoded value (`3.12`).
* Updated the `uv_version` environment variable in the `install dependencies` step to use the `github.event.inputs.uv_version` variable instead of a hardcoded value (`0.7.19`).
=> fix: update workflows inputs

.github/workflows/pull-request.yml, .github/workflows/versioning.yml, uv.lock
This pull request updates the `.github/workflows/versioning.yml` file to improve the versioning workflow by refining cleanup steps, ensuring all necessary files are committed, and adding an additional reviewer for pull requests.
* Replaced the `git rm node_modules` command with `git reset --hard HEAD` for a more robust cleanup process and added a confirmation message "all cleaned up." (`[.github/workflows/versioning.ymlL79-R80](diffhunk://#diff-a939aacba1dba4141eda9eda616ff5e54462b324fbaebe0f8848c06964e67c68L79-R80)`)
* Updated the `git add` command to include `uv.lock` alongside `pyproject.toml`, ensuring all relevant files are staged for version updates. (`[.github/workflows/versioning.ymlL95-R105](diffhunk://#diff-a939aacba1dba4141eda9eda616ff5e54462b324fbaebe0f8848c06964e67c68L95-R105) …
=> ci(workflows): enhance automation and keeping track uv.lock

.github/workflows/release-cp.yml
This pull request updates the `.github/workflows/release-cp.yml` file to switch from a tag-based trigger to a manual workflow dispatch with inputs. It also introduces a GitHub App token for authentication and simplifies the handling of release tags. 
* Replaced the tag-based trigger with a `workflow_dispatch` trigger, allowing manual execution with a required `tag` input.
* Replaced the use of `PTAH_CI_TOKEN` with a dynamically generated GitHub App token for authentication, using the `actions/create-github-app-token@v1` action. [[1]](diffhunk://#diff-fd96c6cb4d9ffec6ca4a96d44bb6ca11d54b1d8f5418dce91fdbb4487b224ba4L25-R39) [[2]](diffhunk://#diff-fd96c6cb4d9ffec6ca4a96d44bb6ca11d54b1d8f5418dce91fdbb4487b224ba4L42-R50) [[3]](diffhunk://#diff-fd96c6cb4d9ffec6ca4a96d44bb6ca11d54b1d8f5418dce91fd …
=> ci(workflows): enhance release branch
