benbenbang/types-confluent-kafka

- confluent_kafka-stubs/cimpl.pyi
> feat: add types - topic partition and admin cli

- confluent_kafka-stubs/cimpl.pyi
Add producer types
resolve #10
> feat: implement producer type

- confluent_kafka-stubs/_util/__init__.pyi
- confluent_kafka-stubs/_util/conversion_util.pyi
- confluent_kafka-stubs/_util/validation_util.pyi
Please include a summary of the change and which issue is fixed.
List any dependencies that are required for this change.
resolve #18, #19 
> feat: implement _util module typings

- confluent_kafka-stubs/admin/_resource.pyi
> feat: implement admin resource typings

- confluent_kafka-stubs/admin/_config.pyi
> feat: implement admin config typing

- confluent_kafka-stubs/admin/_metadata.pyi
> feat: implement admin metadata typings

- confluent_kafka-stubs/_util/__init__.pyi
- confluent_kafka-stubs/_util/validation_util.pyi
- confluent_kafka-stubs/admin/_acl.pyi
- confluent_kafka-stubs/admin/_config.pyi
- confluent_kafka-stubs/admin/_metadata.pyi
> refactor: fix mypy errors

- confluent_kafka-stubs/_util/conversion_util.pyi
- confluent_kafka-stubs/admin/_group.pyi
> feat: implement admin group typings

- confluent_kafka-stubs/admin/_scram.pyi
> feat: implement admin scram typings

- .github/workflows/main.yml
- .github/workflows/pre-hooks.yml
split push event to dedicate yaml, so that Github can get the status
> ci: update and split workflows

- .github/workflows/main.yml
- .github/workflows/mypy-test.yml
- .github/workflows/pyright-test.yml
- confluent_kafka-stubs/__init__.pyi
- confluent_kafka-stubs/_util/validation_util.pyi
- confluent_kafka-stubs/admin/__init__.pyi
- confluent_kafka-stubs/admin/_acl.pyi
- confluent_kafka-stubs/admin/_scram.pyi
- poetry.lock
> ci: add pyright test and clean up ignores

- .github/workflows/publish-pypi.yml
- .github/workflows/publish-testpypi.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
- .releaserc.json
- README.md
> ci: add semantic release workflow

- .releaserc.json
> fix: update wrong branch in releaserc file

- .github/workflows/main.yml
- .github/workflows/typeing-tests.yml
Wrongly put os to arch, fixing it
fix #56 
Any additional context, explanation, or reasoning for the changes made.
If applicable, provide screenshots or images to visually represent the changes.
> fix: wrong architectures in several workflows

- .github/workflows/release.yml
- .github/workflows/releaserc.yml
To make the workflow less confusing, remove the strategy in release and release-rc yml
resolve #60 
> ci: replace strategy & matrix by literal versions

- .github/workflows/publish.yml
> chore: update pypi index for release

- .github/workflows/release.yml
release yml get deleted, adding back
resolve #69
> ci: add missing release yml

- .github/workflows/publish.yml
Add prefix in the release note title
resolve #72 
Checklist:**
> ci: update title by gh in post-release stage

- README.md
- pyproject.toml
fix for the links in docs and toml
resolve #81
> docs: fix links to repo & documentation

- confluent_kafka-stubs/error.pyi
- confluent_kafka-stubs/serialization/__init__.pyi
Please provide a brief description of the changes made in this pull request.
resolve #84 
> feat: implement kafka generic errors

- confluent_kafka-stubs/avro/error.pyi
Implement error types in avro module
resolve #76
> feat: implement avro error typings

- confluent_kafka-stubs/avro/load.pyi
implement `avro.load` helper module's typing
resolve #77
> feat: implement avro load schema funcs typings

- confluent_kafka-stubs/avro/__init__.pyi
- confluent_kafka-stubs/avro/cached_schema_registry_client.pyi
- confluent_kafka-stubs/avro/load.pyi
- confluent_kafka-stubs/avro/serializer/message_serializer.pyi
implement cached schema registry client typings
resolve #75
> feat: implement avro cached sc cli typings

- poetry.lock
- pyproject.toml
Please provide a brief description of the changes made in this pull request.
resolve #90
> chore: update confluent_kafka dep with avro extension

- .github/workflows/typeing-tests.yml
> ci: fix bad condition in test typeings wf

- confluent_kafka-stubs/error.pyi
clean up docstrings due to unable to override them
fix #92 
> refactor: remove unoverride docstrings

- confluent_kafka-stubs/schema_registry/__init__.pyi
- confluent_kafka-stubs/schema_registry/error.pyi
start schema registry module typings
resolve #83 
> feat: implement schema registry module entrypoint & errors typings

- poetry.lock
- pyproject.toml
adding new typing dependencies for development
resolve #108
> build: add requests typings dep to dev

- confluent_kafka-stubs/schema_registry/avro.pyi
- confluent_kafka-stubs/schema_registry/json_schema.pyi
implement sc jsonschema typings
resolve #103
> feat: implement schema registry jsonschema module typings

- confluent_kafka-stubs/schema_registry/__init__.pyi
- confluent_kafka-stubs/schema_registry/protobuf.pyi
implement protobuf module typings
resolve #104
> feat: implement schema registry protobuf module typings

- confluent_kafka-stubs/__init__.pyi
- confluent_kafka-stubs/_model/__init__.pyi
- confluent_kafka-stubs/_util/__init__.pyi
- confluent_kafka-stubs/_util/conversion_util.pyi
- confluent_kafka-stubs/_util/validation_util.pyi
- confluent_kafka-stubs/admin/_config.pyi
- confluent_kafka-stubs/admin/_group.pyi
- confluent_kafka-stubs/admin/_metadata.pyi
- confluent_kafka-stubs/admin/_resource.pyi
- confluent_kafka-stubs/admin/_scram.pyi
- confluent_kafka-stubs/avro/cached_schema_registry_client.pyi
- confluent_kafka-stubs/avro/error.pyi
- confluent_kafka-stubs/avro/load.pyi
- confluent_kafka-stubs/avro/serializer/__init__.pyi
- confluent_kafka-stubs/avro/serializer/message_serializer.pyi
- confluent_kafka-stubs/cimpl.pyi
- confluent_kafka-stubs/deserializing_consumer.pyi
- confluent_kafka-stubs/error.pyi
- confluent_kafka-stubs/kafkatest/__init__.pyi
- confluent_kafka-stubs/kafkatest/verifiable_client.pyi
- confluent_kafka-stubs/kafkatest/verifiable_consumer.pyi
- confluent_kafka-stubs/kafkatest/verifiable_producer.pyi
- confluent_kafka-stubs/schema_registry/__init__.pyi
- confluent_kafka-stubs/schema_registry/error.pyi
- confluent_kafka-stubs/serialization/__init__.pyi
- confluent_kafka-stubs/serializing_producer.pyi
ensure `from __future__ import annotation` are imported
resolve #115
> refactor: ensure import future annotation

- README.md
- compatibility.md
Add table to help easier to understand the compatibility
resolve #117
> docs: add package version compat table

- confluent_kafka-stubs/serialization/__init__.pyi
implement serialization module typings
resolve #120
> feat: implement serialization module typings

- confluent_kafka-stubs/serializing_producer.pyi
implement serializing producer typings
resolve #122
> feat: implement serializing producer typings

- tests/confluent_kafka-stubs/test_cimpli.py
> chore: remove unused test file

- .github/workflows/main.yml
- .github/workflows/typeing-tests.yml
- remove `test` path
- track poetry.lock to see deps changing instead of toml (could be config or version change)
> ci: clean up ci workflows triggers

- .github/CONTRIBUTING.md
- poetry.lock
- pyproject.toml
dependencies clean up
resolve #140
> build: remove unusd test deps

- confluent_kafka-stubs/admin/_acl.pyi
- confluent_kafka-stubs/admin/_config.pyi
- confluent_kafka-stubs/admin/_group.pyi
- confluent_kafka-stubs/admin/_metadata.pyi
- confluent_kafka-stubs/admin/_resource.pyi
- confluent_kafka-stubs/admin/_scram.pyi
refactor admin module
resolve #141
> refactor!: enhance and fix bugs in admin module

- confluent_kafka-stubs/_model/__init__.pyi
enhance model typings
resolve #143
> refactor!: enhance model mod typings

- confluent_kafka-stubs/avro/cached_schema_registry_client.pyi
- confluent_kafka-stubs/avro/error.pyi
- confluent_kafka-stubs/avro/serializer/message_serializer.pyi
enhance avro module
resolve #145
> refactor!: enhance avro mod typings

- confluent_kafka-stubs/avro/cached_schema_registry_client.pyi
small refactor to clean up literal contants
> refactor: simplify literal constants

- pyproject.toml
Clean up old markers in the TOML file
> chore: clean up pytest markers in toml

- poetry.lock
- pyproject.toml
> fix(build): update confluent kafka python client to fix librkafka

- .gitignore
> ops: update gitignore

- confluent_kafka-stubs/schema_registry/json_schema.pyi
As #166 stated, apply fixes for JsonXSerizer
#166 
> fix(serializer): update json serializer signatures

- confluent_kafka-stubs/_model/__init__.pyi
> refactor(_model): drop classvar

- confluent_kafka-stubs/admin/_acl.pyi
- confluent_kafka-stubs/admin/_config.pyi
- confluent_kafka-stubs/admin/_group.pyi
- confluent_kafka-stubs/admin/_metadata.pyi
- confluent_kafka-stubs/admin/_scram.pyi
> refactor(admin): drop classvar in admin module

- confluent_kafka-stubs/error.pyi
> refactor(error): drop classvar in error.py

- confluent_kafka-stubs/avro/cached_schema_registry_client.pyi
- confluent_kafka-stubs/avro/error.pyi
- confluent_kafka-stubs/avro/serializer/__init__.pyi
- confluent_kafka-stubs/avro/serializer/message_serializer.pyi
> refactor(avro): drop classvar in avro module

- confluent_kafka-stubs/schema_registry/error.pyi
- confluent_kafka-stubs/schema_registry/schema_registry_client.pyi
> refactor: drop classvar in schema registry module

- confluent_kafka-stubs/schema_registry/avro.pyi
- confluent_kafka-stubs/schema_registry/json_schema.pyi
> fix: avro & json (de)serializer return types

- .github/workflows/typeing-tests.yml
fix ci runner os arch
resolve #186
> ci: update runner macos version to match its arch

- compatibility.md
update compatibility table for end of 2.2 of confluent_kafka python
and start to introduce signatures that match to 2.3
resolve #189
no typed will be changed in this PR
> docs: update compatibility table

- confluent_kafka-stubs/cimpl.pyi
> fix(cimpl): typo in cimpl stub

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug.yml
⚠️ Noted that the latest version of Confluent Kafka Python is `2.3.x` now.
- For introducing new signatures, please use `feat`
- For fixing compatible signature in `2.2.x`, please use `fix`
Updated guide for contributors w/o poetry and fixed a minor issue with the bug-issue template.
Closes #199 
- [x ] Documentation (Updating or adding documentation, docstrings, etc.)
Any additional context, explanation, or reasoning for the changes made.
If applicable, provide screenshots or images to visually represent the changes.
> docs: contribution guide and issue template

- .github/workflows/pull-request.yml
This pull request includes a small change to the `.github/workflows/pull-request.yml` file. The change adds a new `pull_request_target` event trigger for the `main` branch.
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0R7-R9): Added `pull_request_target` event trigger for the `main` branch.
> ci(workflow): update trigger event

- .github/workflows/pull-request.yml
This pull request includes a change to the GitHub Actions workflow configuration. The change modifies the trigger for pull request workflows.
Workflow configuration update:
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0L4-L6): Replaced `pull_request` trigger with `pull_request_target` trigger to ensure workflows run with the context of the target branch.
> ci(workflow): swap events order

- .github/workflows/release-cp.yml
- .github/workflows/release.yml
- .github/workflows/versioning.yml
temporarily bring back old workflows
If this pull request is related to an issue, please link it here.
> ci(workflow): tmp revert old release workflows

- .github/workflows/pull-request-target.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- .github/workflows/versioning.yml
- .pre-commit-config.yaml
This pull request introduces several updates to GitHub Actions workflows and configuration files, aiming to streamline CI/CD processes and enhance maintainability. Key changes include the migration to reusable workflows, adjustments to permissions, and minor updates to pre-commit configurations.
* [`.github/workflows/pull-request-target.yml`](diffhunk://#diff-ef5ba6d24a13fb62d98bd915d166833f97a83f114f26af945e8d0939e26ec140R1-R29): Added a new workflow for handling pull request target events, including a job for labeling pull requests using the `actions/labeler` action.
* [`.github/workflows/pull-request.yml`](diffhunk://#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0L4-R21): Refactored the workflow to use a reusable pre-commit workflow …
> ci(workflows): split pull requests workflow triggers

- .github/workflows/release.yml
- .github/workflows/versioning.yml
Revert "ci(workflows): split pull requests workflow triggers (#255)"
This reverts commit 1695ad2f373449c95714603acb8c56999fa8b162.
> revert(workflows): drop reusable workflows

- uv.lock
update lock file - self version from 1.3.4 to 1.3.5
> build(uv): upgrade self to 1.3.5
